### ISSUE TITLE
Accessibility with the VoiceOver screen reader

### ISSUE THREAD

**Issue by Piciok** [devandsev/HackerNews-Support#1]
### _This feature might be requested already, [try searching existing issues](https://github.com/devandsev/HackerNews-Support/labels/enhancement) first._
___

**Is your feature request related to a problem? Please describe.**
I really love the idea of the app and its native feel. I believe this would be an excellent solution also for users of the built-in screen reader VoiceOver if a couple improvements were made to make the design feel fully accessible.

**Describe the solution you'd like**
I would like to suggest the following improvements:
- Currently many of the buttons lack labels either entirely or to a sufficient degree where it is unclear to a blind user what the purpose of the button focused is. The result is that it is difficult to tell what the buttons do or what do the numbers ascribed to some of them represent, although I guess those would be the comments and upvotes. It would be ideal if those were supplied with accessibility labels.
- - It would help a lot if the elements on the screen were grouped together semantically so that, from a VoiceOver user's perspective there is as little clutter as possible. The two things that can be done to facilitate this would be:
A. To group the elements of a post together so that the title, domain, author, time of posting as well as the comments' and upvotes' count are discovered through accessibility focus as one element; and
B. assign all of the action buttons as rotor actions. This way, the accessibility focus will skip over them when navigating sequentially by swiping from left to right but they will be available on a given post after flicking down with one finger.
- The most important feature of the app is the innovative threads view. I really love the idea but currently the structure is not very clearly presented when using VoiceOver. It doesn't seem to be possible to expand and collapse threads very efficiently and it also is not possible to ascertain at which level in the hierarchy a given comment is located. It would be great if an option was given of collapsing and expanding threads by tapping on the parent comment or if the swiping gestures accessible to VoiceOver were implemented (three-finger swipe left and right). Also the comment level number, the poster's username, the time of posting and the number of upvotes could be grouped together as described  before.
- Additionally, it would be perfect if aspects such as the order of information spoken when focusing an item or order of actions on the rotor could be configured by the user.

**Describe alternatives you've considered**
I have tried using other HN clients before but most of them do not seem to be in active development.

**Additional context**
iOS is the mobile OS of choice for many blind and partially sighted users around the world. Many of those users share their input and obtain useful information from Hacker News. Improving accessibility of your app would give them a new handy tool to do that in a convenient way.
Below, you will find a handful of resources that might assist you in starting your accessibility journey:
The official Apple Developer page on accessibility:
https://developer.apple.com/accessibility/
Appt - a repository of accessible code patterns for mobile apps:
https://appt.org/
Applevis - a helpful community where users and developers will be more than happy to provide advice and testing:
https://applevis.com/
Dystopia for Reddit - an unofficial client for Reddit that provides an excellent accessible interface and could help you as an example of the app I have in mind:
https://testflight.apple.com/join/4MJtN4FB
If you are using either Mastodon or Twitter, try to search for the #365DaysofIOSAccessibility hashtag where bits and pieces of excellent accessibility advice are provided every day in a bite-sized, easy to grasp form.

Once again, thank you for creating your app and I look forward to the journey ahead.

**Comment by devandsev** [comment]
Implemented in version `1.3 (1)`. Added labels, grouping (the order is not customizable yet), rotor actions, collapsing/expanding by tapping.

The core idea of the app relies heavily on the visual cues and interactive animations, the layout of the screen changes frequently. Unfortunately this approach doesn't work well with VoiceOver, but this update should improve the navigation. Traditional approach of displaying a static list of comments may work better in this case ([HACK](https://itunes.apple.com/us/app/hack-for-hacker-news-developer/id1464477788?mt=8) and [Octal](https://itunes.apple.com/us/app/id1308885491) come to mind. Full list: https://github.com/devandsev/awesome-hacker-news#ios).

**Comment by Piciok** [comment]
Hello and my apologies for the late response.

Thank you for the changes you have introduced and all of your work. It is really appreciated. The app is much clearer to navigate now.

I am not sure how to help further regarding the comments section. I guess I can't imagine the technical difficulty posed by the implementation, but I have shared the app on my Mastodon and encouraged the wider community to get involved in the discussion. Maybe we'll come up with a viable solution by way of collective thinking.

Thank you for the tip regarding other apps as well. There has been a lot of success with Octal but I am still looking forward to the other changes you were planning to introduce - the greater choice, the better!

Thanks again!
