### ISSUE TITLE
“Restore defaults boards” button

### ISSUE THREAD

**Issue by canthonytucci** [devandsev/HackerNews-Support#2]
Would be nice to have one. For those who deleted them and regret it. 

I’ve found the add “standard board” thing. It would be nice to get them all at once and without typing.

**Comment by canthonytucci** [comment]
I’ve found the add “standard board” thing. It would be nice to get them all at once and without typing.

**Comment by devandsev** [comment]
Implemented in version `1.2 (4)`. Enter editing mode by tapping "Edit" and you'll see the restore button.
