### ISSUE TITLE
Option to have long press on post open the share menu

### ISSUE THREAD

**Issue by rben01** [devandsev/HackerNews-Support#4]
**Is your feature request related to a problem? Please describe.**
When viewing the list of posts, I'm unable to easily share a post

**Describe the solution you'd like**
Long press to share

**Describe alternatives you've considered**
A share button on posts, similar to the upvote button

**Additional context**
None

**Comment by devandsev** [comment]
Implemented in version 1.4 (1).

Added custom actions to share items from the list of submissions (Settings -> Controls & behaviors -> Threads section).

<img src="https://github.com/devandsev/HackerNews-Support/assets/17564071/5e597887-02cd-4a22-81ef-bb72911b3cff" width="300">

<img src="https://github.com/devandsev/HackerNews-Support/assets/17564071/0de839f0-abc1-47af-8d7b-80f09ce58e7a" width="300">
