### ISSUE TITLE
Slow or unreliable connection

### ISSUE THREAD

**Issue by KTallguy** [devandsev/HackerNews-Support#7]
### _This bug might be reported already, [try searching existing issues](https://github.com/devandsev/HackerNews-Support/labels/bug) first._
___

**Describe the bug**
The app starts but the posts appear very slowly when refreshed (1+ mins)

Also received an error once, unsure if related. See attached screenshot. 

**To Reproduce**
1. Open the app 
2. Refresh any category of posts 

**Expected behavior**
The posts load quickly as before. 

**Device & Versions:**
 - Device: iPhone 15x pro 
 - Is the device jailbroken: no
 - iOS version: 17.4.1
 - App version: 1.4.2

**Screenshots & Video**
![IMG_1629](https://github.com/devandsev/HackerNews-Support/assets/9643699/d072978f-55b3-455e-a2dd-fc9ac0ce69ca)

**Additional context**

**Comment by Adlopa** [comment]
Same problem here, both with loading content on app launch and when viewing posts. I’ve yet to get the error message, though. Not sure when this started for me, but certainly within the last few days. 

Device: iPhone 14 Pro Max
Is the device jailbroken: no
iOS version: 17.5.1
App version: 1.4.2 (1)

**Comment by misterWiz** [comment]
Posts are loading extremely slowly for me as well. I’ve never actually waited long enough for them to appear, I just see a blank feed and spinning wheel.This started about a week ago.

iPhone 15 pro
iOS 17.4.1
App version 1.4.2 (1)
Not jailbroken

**Comment by devandsev** [comment]
Thanks all for reporting!

Something changed in how Firebase is working on the server side, because performance issues started without any recent changes on the client side.

I've tried an alternative way of requesting Firebase items, and so far it seems to work much better. **New app version is in review and should be available soon**.

**Comment by KTallguy** [comment]
@devandsev 
I have your new version now and it works perfectly (just as before). Thank you! 
Strangely, even before I got the new version the loading seemed to be improved. In any case, thank you very much for addressing this issue so quickly. You’ve made a very nice app.

**Comment by devandsev** [comment]
@KTallguy Thanks! I'll keep this issue open for a bit, feel free to report any changes here.

AppStore ratings/reviews are appreciated, as I got some one star reviews for this issue before I could even investigate it 😅

**Comment by Adlopa** [comment]
The app also seems to be back to normal for me with v1.5. Thanks for the rapid fix!

**Comment by devandsev** [comment]
Fixed in version 1.5 (1).
